package ddl

import (
	"fmt"
	"strings"
)

type GaussDBRenderer struct{}

func (r *GaussDBRenderer) Render(ir *TableIR) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", ir.TableName))

	totalItems := len(ir.Columns) + countPk(ir) + len(ir.Indexes) + len(ir.ForeignKeys)
	itemIdx := 0

	for _, col := range ir.Columns {
		sb.WriteString("  ")
		sb.WriteString(col.Name)
		sb.WriteString(" ")
		sb.WriteString(r.renderType(col))
		if !col.Nullable {
			sb.WriteString(" NOT NULL")
		}
		if col.DefaultValue != "" {
			sb.WriteString(fmt.Sprintf(" DEFAULT '%s'", col.DefaultValue))
		}
		if itemIdx < totalItems-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
		itemIdx++
	}

	pks := ir.primaryKeys()
	if len(pks) > 0 {
		sb.WriteString("  PRIMARY KEY (")
		for i, pk := range pks {
			sb.WriteString(pk)
			if i < len(pks)-1 {
				sb.WriteString(", ")
			}
		}
		sb.WriteString(")")
		if itemIdx < totalItems-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
		itemIdx++
	}

	for _, idx := range ir.Indexes {
		idxType := "INDEX"
		if idx.Type == "UNIQUE" {
			idxType = "UNIQUE INDEX"
		}
		sb.WriteString(fmt.Sprintf("  %s %s (", idxType, idx.Name))
		for j, col := range idx.Columns {
			sb.WriteString(col.Name)
			if col.Order == "DESC" {
				sb.WriteString(" DESC")
			}
			if j < len(idx.Columns)-1 {
				sb.WriteString(", ")
			}
		}
		sb.WriteString(")")
		if itemIdx < totalItems-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
		itemIdx++
	}

	for _, fk := range ir.ForeignKeys {
		sb.WriteString(fmt.Sprintf("  CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
			fk.Name, fk.ColumnName, fk.RefTableName, fk.RefColumn))
		if itemIdx < totalItems-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
		itemIdx++
	}

	sb.WriteString(")")

	if ir.TableComment != "" {
		sb.WriteString(fmt.Sprintf(";\nCOMMENT ON TABLE %s IS '%s'", ir.TableName, ir.TableComment))
	}

	for _, col := range ir.Columns {
		if col.Comment != "" {
			sb.WriteString(fmt.Sprintf(";\nCOMMENT ON COLUMN %s.%s IS '%s'", ir.TableName, col.Name, col.Comment))
		}
	}

	sb.WriteString(";")
	return sb.String()
}

func (r *GaussDBRenderer) renderType(col ColumnIR) string {
	lt := strings.ToUpper(col.LogicalType)
	switch lt {
	case "VARCHAR":
		length := 255
		if col.TypeLength != nil {
			length = *col.TypeLength
		}
		return fmt.Sprintf("VARCHAR(%d)", length)
	case "DECIMAL":
		length := 18
		scale := 2
		if col.TypeLength != nil {
			length = *col.TypeLength
		}
		if col.TypeScale != nil {
			scale = *col.TypeScale
		}
		return fmt.Sprintf("DECIMAL(%d,%d)", length, scale)
	case "BIGINT":
		if col.IsPrimaryKey {
			return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
		}
		return "BIGINT"
	case "INT":
		return "INT"
	case "FLOAT":
		return "FLOAT"
	case "DOUBLE":
		return "DOUBLE"
	case "DATE":
		return "DATE"
	case "DATETIME":
		return "TIMESTAMP"
	case "TIMESTAMP":
		return "TIMESTAMP"
	case "TEXT":
		return "CLOB"
	case "BOOLEAN":
		return "BOOLEAN"
	case "JSON":
		return "JSON"
	default:
		return lt
	}
}

func countPk(ir *TableIR) int {
	if len(ir.primaryKeys()) > 0 {
		return 1
	}
	return 0
}
